---
- name: Build AWX inventory
  awx.awx.inventory:
    name: "manual_inventory"
    organization: tb4ena
    controller_host: "awxdev.tb4ena.com"
    controller_username: "awxuser"
    controller_oauthtoken: "4Z4XdkU1hxv6u3To5q0ANTSKR9F3Kg"
    validate_certs: false
    state: present

- name: Configure inventory source
  awx.awx.inventory_source:
    name: "manual_inventory_source"
    inventory: "manual_inventory"
    organization: tb4ena
    controller_host: "awxdev.tb4ena.com"
    controller_username: "awxuser"
    controller_oauthtoken: "4Z4XdkU1hxv6u3To5q0ANTSKR9F3Kg"
    validate_certs: false
    overwrite: true
    overwrite_vars: true
    update_on_launch: true
    source: scm
    source_project: manual_inventory_main
    source_path: "inventory_source/inventory.yml"
    state: present

- name: Update source
  awx.awx.inventory_source_update:
    name: "manual_inventory_source"
    inventory: "manual_inventory"
    organization: tb4ena
    controller_host: "awxdev.tb4ena.com"
    controller_username: "awxuser"
    controller_oauthtoken: "4Z4XdkU1hxv6u3To5q0ANTSKR9F3Kg"
    validate_certs: false
